"""Document tool for deterministic DOCX generation.

Uses python-docx to create professional Word documents
from synthesized content.
"""

import logging
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.config import OUTPUT_DIR

logger = logging.getLogger(__name__)


def sanitize_filename(name: str) -> str:
    """Create a safe filename from a string."""
    # Remove unsafe characters
    safe = re.sub(r'[^\w\s-]', '', name.lower())
    safe = re.sub(r'[\s]+', '_', safe.strip())
    # Truncate to reasonable length
    return safe[:50] if safe else "document"


def generate_docx(
    title: str,
    document_type: str,
    assumptions: list[str],
    content: str,
    goal: str,
) -> str:
    """Generate a professional DOCX document.

    Args:
        title: Document title
        document_type: Type of document being generated
        assumptions: List of assumptions made
        content: The synthesized document content
        goal: The interpreted goal

    Returns:
        The filename of the generated document.
    """
    OUTPUT_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_type = sanitize_filename(document_type)
    filename = f"agentdoc_{safe_type}_{timestamp}.docx"
    filepath = OUTPUT_DIR / filename

    doc = Document()

    # --- Styles ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # --- Title ---
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- Subtitle ---
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Document Type: {document_type.replace('_', ' ').title()}")
    run.font.size = Pt(12)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # --- Date ---
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    date_run.font.size = Pt(10)
    date_run.font.color.rgb = RGBColor(130, 130, 130)

    doc.add_paragraph()  # Spacer

    # --- Goal / Executive Summary ---
    if goal:
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(goal)

    # --- Assumptions ---
    if assumptions:
        doc.add_heading("Key Assumptions", level=1)
        for assumption in assumptions:
            p = doc.add_paragraph(assumption, style='List Bullet')
            p.paragraph_format.space_after = Pt(4)

    # --- Main Content ---
    _add_content_sections(doc, content)

    # --- Footer ---
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by AgentDoc — Autonomous Document Generation Agent")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)
    footer_run.font.italic = True

    doc.save(str(filepath))
    logger.info("Generated DOCX: %s", filename)
    return filename


def _add_content_sections(doc: Document, content: str) -> None:
    """Parse and add content sections to the document.

    Handles headings (## / ###), bullet points (- / *), numbered lists,
    and tables (| ... |).
    """
    lines = content.split("\n")
    i = 0
    in_table = False
    table_rows: list[list[str]] = []

    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            if in_table and table_rows:
                _add_table(doc, table_rows)
                table_rows = []
                in_table = False
            i += 1
            continue

        # Table detection
        if line.startswith("|") and line.endswith("|"):
            # Skip separator rows
            if re.match(r'^\|[\s\-:|]+\|$', line):
                i += 1
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            table_rows.append(cells)
            in_table = True
            i += 1
            continue

        # Flush any pending table
        if in_table and table_rows:
            _add_table(doc, table_rows)
            table_rows = []
            in_table = False

        # Heading level 1 (##)
        if line.startswith("## "):
            heading_text = line[3:].strip()
            # Clean any markdown bold markers
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=1)
            i += 1
            continue

        # Heading level 2 (###)
        if line.startswith("### "):
            heading_text = line[4:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=2)
            i += 1
            continue

        # Heading level 3 (####)
        if line.startswith("#### "):
            heading_text = line[5:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=3)
            i += 1
            continue

        # Bullet points
        if line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            text = _clean_markdown(text)
            doc.add_paragraph(text, style='List Bullet')
            i += 1
            continue

        # Numbered list (e.g., "1. ", "2. ")
        match = re.match(r'^(\d+)\.\s+(.+)', line)
        if match:
            text = _clean_markdown(match.group(2))
            doc.add_paragraph(text, style='List Number')
            i += 1
            continue

        # Regular paragraph
        text = _clean_markdown(line)
        if text:
            doc.add_paragraph(text)

        i += 1

    # Flush final table
    if table_rows:
        _add_table(doc, table_rows)


def _add_table(doc: Document, rows: list[list[str]]) -> None:
    """Add a table to the document."""
    if not rows:
        return

    num_cols = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=num_cols)
    table.style = 'Light Grid Accent 1'

    for r_idx, row_data in enumerate(rows):
        for c_idx, cell_text in enumerate(row_data):
            if c_idx < num_cols:
                cell = table.cell(r_idx, c_idx)
                cell.text = _clean_markdown(cell_text)
                # Bold header row
                if r_idx == 0:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True

    doc.add_paragraph()  # Spacer after table


def _clean_markdown(text: str) -> str:
    """Remove common markdown formatting from text."""
    # Remove bold markers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    # Remove italic markers
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    # Remove inline code
    text = re.sub(r'`(.+?)`', r'\1', text)
    # Remove markdown links, keep text
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    return text.strip()
