"""Document tool for deterministic DOCX generation.

Uses python-docx to create professional Word documents
from synthesized content.
"""

import logging
import re
from datetime import datetime
from pathlib import Path
import markdown
from fpdf import FPDF
from fpdf import FPDF
from fpdf.enums import XPos, YPos

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

import time
from app.config import OUTPUT_DIR
from app.llm.budget_guard import check_budget_pdf

logger = logging.getLogger(__name__)


def sanitize_filename(name: str) -> str:
    """Create a safe filename from a string."""
    # Remove unsafe characters
    safe = re.sub(r'[^\w\s-]', '', name.lower())
    safe = re.sub(r'[\s]+', '_', safe.strip())
    # Truncate to reasonable length
    return safe[:50] if safe else "document"


def generate_docx(
    title: str,
    document_type: str,
    assumptions: list[str],
    content: str,
    goal: str,
    format_ext: str = "docx"
) -> str:
    """Generate a professional document in the requested format.

    Args:
        title: Document title
        document_type: Type of document being generated
        assumptions: List of assumptions made
        content: The synthesized document content
        goal: The interpreted goal

    Returns:
        The filename of the generated document.
    """
    # Run lightweight editorial cleanup pass
    content = _editorial_cleanup_pass(content)
    
    OUTPUT_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_type = sanitize_filename(document_type)
    
    # Normalize format
    fmt = format_ext.lower().strip('.')
    if fmt not in ["docx", "pdf", "html", "md", "markdown"]:
        fmt = "docx"
        
    filename = f"agentdoc_{safe_type}_{timestamp}.{fmt}"
    filepath = OUTPUT_DIR / filename

    start_build_time = time.time()
    
    if fmt in ["md", "markdown"]:
        res = _generate_markdown(filepath, title, document_type, assumptions, content, goal, filename)
        check_budget_pdf(time.time() - start_build_time, fmt)
        return res
    elif fmt == "html":
        res = _generate_html(filepath, title, document_type, assumptions, content, goal, filename)
        check_budget_pdf(time.time() - start_build_time, fmt)
        return res
    elif fmt == "pdf":
        res = _generate_pdf(filepath, title, document_type, assumptions, content, goal, filename)
        check_budget_pdf(time.time() - start_build_time, fmt)
        return res

    doc = Document()

    # --- Page Setup & Margins ---
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # --- Styles ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'
    font.size = Pt(11)
    style.paragraph_format.space_after = Pt(12)
    style.paragraph_format.line_spacing = 1.15

    # --- Title ---
    title_para = doc.add_heading(level=0)
    title_run = title_para.add_run(title)
    title_run.font.name = 'Calibri'
    title_run.font.size = Pt(24)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- Subtitle ---
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Document Type: {document_type.replace('_', ' ').title()}")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # --- Date ---
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    date_run.font.size = Pt(11)
    date_run.font.color.rgb = RGBColor(130, 130, 130)

    doc.add_paragraph()  # Spacer

    # --- Goal / Executive Summary ---
    if goal:
        h = doc.add_heading(level=1)
        r = h.add_run("Executive Summary")
        r.font.color.rgb = RGBColor(41, 128, 185) # Professional Blue
        exec_summary = doc.add_paragraph(goal)
        exec_summary.paragraph_format.space_after = Pt(12)

    # --- Assumptions ---
    if assumptions:
        doc.add_heading("Key Assumptions", level=1)
        for assumption in assumptions:
            p = doc.add_paragraph(assumption, style='List Bullet')
            p.paragraph_format.space_after = Pt(4)

    # --- Main Content ---
    _add_content_sections(doc, content)

    # --- Footer ---
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by AgentDoc — Autonomous Document Generation Agent")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)
    footer_run.font.italic = True

    doc.save(str(filepath))
    logger.info("Generated DOCX: %s", filename)
    check_budget_pdf(time.time() - start_build_time, fmt)
    return filename


def _generate_markdown(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    lines = [
        f"# {title}",
        f"**Document Type:** {document_type.replace('_', ' ').title()}",
        f"**Generated:** {datetime.now().strftime('%B %d, %Y')}",
        ""
    ]
    if goal:
        lines.extend(["## Executive Summary", goal, ""])
    if assumptions:
        lines.extend(["## Key Assumptions"])
        lines.extend([f"- {a}" for a in assumptions])
        lines.extend([""])
        
    lines.append(content)
    lines.extend([
        "",
        "---",
        "*Generated by AgentDoc — Autonomous Document Generation Agent*"
    ])
    
    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filename


def _generate_html(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    md_text = _generate_markdown(filepath, title, document_type, assumptions, content, goal, filename)
    # Read the markdown back
    md_content = filepath.read_text(encoding="utf-8")
    
    html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
    
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
    h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
    h2 {{ color: #34495e; margin-top: 30px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
    th {{ background-color: #f8f9fa; font-weight: 600; }}
    hr {{ border: 0; border-top: 1px solid #eee; margin: 40px 0; }}
    .footer {{ color: #888; font-size: 0.9em; text-align: center; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""

    filepath.write_text(html, encoding="utf-8")
    return filename


def _to_latin1(text: str) -> str:
    """Sanitize unicode string to latin-1, replacing unsupported characters with equivalents."""
    replacements = {
        '\u2014': '-',   # em-dash
        '\u2013': '-',   # en-dash
        '\u201c': '"',   # left double quote
        '\u201d': '"',   # right double quote
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u2022': '\x95', # bullet point
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    return text.encode('latin-1', 'replace').decode('latin-1')


class PDFTheme:
    # Margins (mm)
    MARGIN_LEFT = 25.4
    MARGIN_RIGHT = 25.4
    MARGIN_TOP = 25.4
    MARGIN_BOTTOM = 25.4
    
    # Grayscale-friendly Sage & Green Palette (RGB)
    COLOR_PRIMARY = (27, 63, 50)       # Dark Forest Green spine & main headers
    COLOR_SECONDARY = (92, 107, 98)    # Slate / Medium Sage Grey for secondary headers & subtitles
    COLOR_TEXT = (40, 44, 42)          # Off-black charcoal for body text
    COLOR_MUTED = (136, 140, 138)      # Muted grey-sage for headers/footers
    COLOR_DIVIDER = (218, 224, 220)    # Light grey-green for dividers & borders
    
    # Table Styling
    COLOR_TABLE_HEADER_FILL = (27, 63, 50)    # Forest Green Table Header
    COLOR_TABLE_HEADER_TEXT = (255, 255, 255)   # White Header Text
    COLOR_TABLE_CELL_FILL_EVEN = (243, 245, 244) # Very soft gray-green background rows
    COLOR_TABLE_BORDER = (218, 224, 220)       # Light border lines
    
    # Typography
    FONT_FAMILY = "helvetica"
    
    # Font Sizes (pt)
    SIZE_TITLE = 26
    SIZE_SUBTITLE = 12
    SIZE_H1 = 15
    SIZE_H2 = 12.5
    SIZE_H3 = 11
    SIZE_BODY = 10
    SIZE_FOOTER = 8
    
    # Line Heights (mm)
    LEAD_TITLE = 11
    LEAD_SUBTITLE = 8
    LEAD_H1 = 8
    LEAD_H2 = 7
    LEAD_H3 = 6
    LEAD_BODY = 6
    LEAD_FOOTER = 5.5


class PDF(FPDF):
    def __init__(self, doc_title="", doc_type="", gen_date="", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.doc_title = doc_title
        self.doc_type = doc_type
        self.gen_date = gen_date
        # Enable alias for total page count placeholder {nb}
        self.alias_nb_pages()

    def check_page_break(self, height):
        """Force a page break if remaining vertical space is less than height."""
        if self.get_y() + height > self.h - self.b_margin:
            self.add_page()

    def header(self):
        # Header runs only on content pages (page > 1)
        if self.page_no() > 1:
            current_l_margin = self.l_margin
            current_r_margin = self.r_margin
            self.set_left_margin(PDFTheme.MARGIN_LEFT)
            self.set_right_margin(PDFTheme.MARGIN_RIGHT)
            
            self.set_y(12)
            self.set_font(PDFTheme.FONT_FAMILY, "I", PDFTheme.SIZE_FOOTER)
            self.set_text_color(*PDFTheme.COLOR_MUTED)
            
            # Left Header: title & type
            clean_type = self.doc_type.replace('_', ' ').title()
            header_text = f"AgentDoc | {self.doc_title} ({clean_type})"
            self.cell(0, 8, _to_latin1(header_text), align="L")
            
            # Right Header: Date
            self.set_x(self.w - PDFTheme.MARGIN_RIGHT - 50)
            self.cell(50, 8, _to_latin1(self.gen_date), align="R")
            
            # Draw header line divider
            line_y = 20
            self.set_draw_color(*PDFTheme.COLOR_DIVIDER)
            self.set_line_width(0.3)
            self.line(PDFTheme.MARGIN_LEFT, line_y, self.w - PDFTheme.MARGIN_RIGHT, line_y)
            
            self.set_left_margin(current_l_margin)
            self.set_right_margin(current_r_margin)
            self.set_y(PDFTheme.MARGIN_TOP)

    def footer(self):
        # Footer runs only on content pages (page > 1)
        if self.page_no() > 1:
            current_l_margin = self.l_margin
            current_r_margin = self.r_margin
            self.set_left_margin(PDFTheme.MARGIN_LEFT)
            self.set_right_margin(PDFTheme.MARGIN_RIGHT)
            
            # Draw footer line divider
            line_y = self.h - 18
            self.set_draw_color(*PDFTheme.COLOR_DIVIDER)
            self.set_line_width(0.3)
            self.line(PDFTheme.MARGIN_LEFT, line_y, self.w - PDFTheme.MARGIN_RIGHT, line_y)
            
            self.set_y(-15)
            self.set_font(PDFTheme.FONT_FAMILY, "I", PDFTheme.SIZE_FOOTER)
            self.set_text_color(*PDFTheme.COLOR_MUTED)
            
            self.cell(0, 10, _to_latin1("Generated by AgentDoc Services"), align="L")
            self.set_x(self.w - PDFTheme.MARGIN_RIGHT - 40)
            self.cell(40, 10, _to_latin1(f"Page {self.page_no()} of {{nb}}"), align="R")
            
            self.set_left_margin(current_l_margin)
            self.set_right_margin(current_r_margin)


# ---------------- VECTOR GRAPHIC ICONS next to HEADINGS ----------------
def draw_heading_icon(pdf, section_type, x, y, size=4.0):
    """Draw a clean, crisp vector graphic icon based on the semantic section type."""
    if section_type == "objectives":
        # Target Concentric Circles
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        pdf.circle(x + size/2, y + size/2, size/2)
        pdf.circle(x + size/2, y + size/2, size/4)
    elif section_type == "recommendations":
        # Next Steps Horizontal Arrow
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.6)
        pdf.line(x, y + size/2, x + size - 0.5, y + size/2)
        pdf.line(x + size - 2.0, y + size/2 - 1.5, x + size - 0.5, y + size/2)
        pdf.line(x + size - 2.0, y + size/2 + 1.5, x + size - 0.5, y + size/2)
    elif section_type == "risks":
        # Warning/Alert Triangle
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        p1 = (x + size/2, y)
        p2 = (x, y + size)
        p3 = (x + size, y + size)
        pdf.line(p1[0], p1[1], p2[0], p2[1])
        pdf.line(p2[0], p2[1], p3[0], p3[1])
        pdf.line(p3[0], p3[1], p1[0], p1[1])
        pdf.set_line_width(0.5)
        pdf.line(x + size/2, y + 1.2, x + size/2, y + size - 1.5)
        pdf.circle(x + size/2, y + size - 0.8, 0.2)
    elif section_type == "timeline":
        # Calendar Grid
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        pdf.rect(x, y + 0.8, size, size - 0.8, "D")
        pdf.line(x, y + 1.8, x + size, y + 1.8)
        pdf.line(x + size/3, y, x + size/3, y + 0.8)
        pdf.line(x + 2*size/3, y, x + 2*size/3, y + 0.8)
    elif section_type == "metrics":
        # Bar Chart Graph
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        pdf.line(x, y, x, y + size)
        pdf.line(x, y + size, x + size, y + size)
        pdf.set_line_width(0.6)
        pdf.line(x + 1.2, y + size, x + 1.2, y + size - 2.0)
        pdf.line(x + 2.4, y + size, x + 2.4, y + size - 3.2)
        pdf.line(x + 3.6, y + size, x + 3.6, y + size - 1.2)
    elif section_type == "deliverables":
        # Checklist Square with Tick
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        pdf.rect(x, y + 0.2, size - 0.4, size - 0.4, "D")
        pdf.set_line_width(0.5)
        pdf.line(x + 0.8, y + size/2, x + size/2.5, y + size - 1.2)
        pdf.line(x + size/2.5, y + size - 1.2, x + size - 1.0, y + 1.0)
    elif section_type == "assumptions":
        # Overlapping Rectangles (Layers)
        pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
        pdf.set_line_width(0.4)
        pdf.rect(x, y + 1.2, size - 1.2, size - 1.2, "D")
        pdf.rect(x + 1.2, y, size - 1.2, size - 1.2, "D")


# ---------------- ACCORDION PHASE CARDS ----------------
def draw_phase_card(pdf, phase_title, lines):
    """Draw a clean, consulting-grade Phase banner card for timelines."""
    # Measure line wraps to calculate total card body height
    pdf.set_font(PDFTheme.FONT_FAMILY, "", 9)
    w_content = pdf.epw - 12  # Padding margin space
    
    total_lines = 0
    for line in lines:
        stripped = line.strip().replace('**', '').replace('*', '')
        # Check if line contains a sub-label
        parts = re.split(r'^(\*?\*?Objective:\*?\*?|\*?\*?Deliverables:\*?\*?|\*?\*?Timeline:\*?\*?|\*?\*?Budget:\*?\*?)', stripped, flags=re.IGNORECASE)
        if len(parts) >= 3:
            stripped = f"{parts[1].strip()} {parts[2].strip()}"
        l_wrap = len(pdf.multi_cell(w_content, 4.5, _to_latin1(stripped), dry_run=True, output="LINES"))
        total_lines += l_wrap
        
    body_h = (total_lines * 4.5) + (len(lines) - 1) * 2 + 8
    total_h = 8 + body_h
    
    # Check page break boundary
    pdf.check_page_break(total_h + 6)
    
    x = pdf.get_x()
    y = pdf.get_y()
    w = pdf.epw
    
    # Draw dark forest green header banner
    pdf.set_fill_color(*PDFTheme.COLOR_PRIMARY)
    pdf.rect(x, y, w, 8, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(PDFTheme.FONT_FAMILY, "B", 9.5)
    pdf.set_xy(x + 4, y + 2)
    pdf.cell(w - 8, 4, _to_latin1(phase_title.upper()))
    
    # Draw soft gray-green body fill (#F4F6F4)
    pdf.set_fill_color(*PDFTheme.COLOR_TABLE_CELL_FILL_EVEN)
    pdf.rect(x, y + 8, w, body_h, "F")
    
    # Draw thin divider border
    pdf.set_draw_color(*PDFTheme.COLOR_DIVIDER)
    pdf.set_line_width(0.3)
    pdf.rect(x, y, w, total_h, "D")
    
    current_y = y + 12
    for line in lines:
        pdf.set_xy(x + 4, current_y)
        stripped = line.strip()
        
        # Highlight sub-labels
        parts = re.split(r'^(\*?\*?Objective:\*?\*?|\*?\*?Deliverables:\*?\*?|\*?\*?Timeline:\*?\*?|\*?\*?Budget:\*?\*?)', stripped, flags=re.IGNORECASE)
        if len(parts) >= 3:
            label = parts[1].replace('**', '').replace('*', '').strip()
            val = parts[2].strip()
            
            pdf.set_font(PDFTheme.FONT_FAMILY, "B", 9)
            pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
            pdf.write(4.5, _to_latin1(f"{label} "))
            
            pdf.set_font(PDFTheme.FONT_FAMILY, "", 9)
            pdf.set_text_color(*PDFTheme.COLOR_TEXT)
            pdf.multi_cell(w - 20, 4.5, _to_latin1(val), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.set_font(PDFTheme.FONT_FAMILY, "", 9)
            pdf.set_text_color(*PDFTheme.COLOR_TEXT)
            pdf.multi_cell(w - 8, 4.5, _to_latin1(stripped.replace('**', '').replace('*', '')), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
        current_y = pdf.get_y() + 2
        
    pdf.set_y(y + total_h + 4)


# ---------------- SHADED BRIEFING PANEL (EXECUTIVE SUMMARY) ----------------
def render_executive_summary_panel(pdf, blocks):
    """Render the collected executive summary content in a single beautifully shaded panel with a left green accent spine."""
    lines = []
    for b in blocks:
        if b["type"] == "paragraph":
            lines.extend([l.strip() for l in b["content"].split("\n") if l.strip()])
        elif b["type"] == "list":
            items = parse_list_items(b["content"])
            for item in items:
                prefix = f"{item['marker']}. " if item["is_number"] else "\x95 "
                lines.append(f"{prefix}{item['text']}")
                
    if not lines:
        return
        
    pdf.set_font(PDFTheme.FONT_FAMILY, "I", 10.5)
    w_content = pdf.epw - 12
    
    total_lines = 0
    for line in lines:
        l_wrap = len(pdf.multi_cell(w_content, 5.5, _to_latin1(line), dry_run=True, output="LINES"))
        total_lines += l_wrap
        
    box_h = (total_lines * 5.5) + (len(lines) - 1) * 2 + 8
    
    # Check page overflow
    pdf.check_page_break(box_h + 6)
    
    x = pdf.get_x()
    y = pdf.get_y()
    w = pdf.epw
    
    # Draw soft light sage background (#EDF3EF)
    pdf.set_fill_color(237, 243, 239)
    pdf.rect(x, y, w, box_h, "F")
    
    # Draw left Forest Green accent strip (2mm)
    pdf.set_fill_color(*PDFTheme.COLOR_PRIMARY)
    pdf.rect(x, y, 2.0, box_h, "F")
    
    # Draw thin divider line
    pdf.set_draw_color(*PDFTheme.COLOR_DIVIDER)
    pdf.set_line_width(0.3)
    pdf.rect(x, y, w, box_h, "D")
    
    current_y = y + 4
    for line in lines:
        pdf.set_xy(x + 6, current_y)
        
        if line.startswith("\x95 "):
            pdf.set_font(PDFTheme.FONT_FAMILY, "B", 10.5)
            pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
            pdf.write(5.5, _to_latin1("\x95  "))
            pdf.set_font(PDFTheme.FONT_FAMILY, "I", 10.5)
            pdf.set_text_color(*PDFTheme.COLOR_TEXT)
            pdf.multi_cell(w_content - 4, 5.5, _to_latin1(line[2:]), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        elif re.match(r'^\d+\.\s+', line):
            m = re.match(r'^(\d+\.)\s+(.+)', line)
            prefix = m.group(1)
            body = m.group(2)
            pdf.set_font(PDFTheme.FONT_FAMILY, "B", 10.5)
            pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
            pdf.write(5.5, _to_latin1(f"{prefix}  "))
            pdf.set_font(PDFTheme.FONT_FAMILY, "I", 10.5)
            pdf.set_text_color(*PDFTheme.COLOR_TEXT)
            pdf.multi_cell(w_content - 6, 5.5, _to_latin1(body), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.set_font(PDFTheme.FONT_FAMILY, "I", 10.5)
            pdf.set_text_color(*PDFTheme.COLOR_TEXT)
            pdf.multi_cell(w_content, 5.5, _to_latin1(line), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
        current_y = pdf.get_y() + 2
        
    pdf.set_y(y + box_h + 6)


# ---------------- SHADED CALLOUT PANEL (OBJECTIVES / CALLOUTS) ----------------
def render_callout_box(pdf, text, border_color, fill_color, text_style=""):
    """Render a clean shaded box with a left accent border for general callouts."""
    pdf.set_font(PDFTheme.FONT_FAMILY, text_style, 10)
    w_content = pdf.epw - 12
    l_wrap = len(pdf.multi_cell(w_content, 5.5, _to_latin1(text), dry_run=True, output="LINES"))
    box_h = (l_wrap * 5.5) + 8
    
    pdf.check_page_break(box_h + 6)
    
    x = pdf.get_x()
    y = pdf.get_y()
    w = pdf.epw
    
    # Background fill
    pdf.set_fill_color(*fill_color)
    pdf.rect(x, y, w, box_h, "F")
    
    # Left border
    pdf.set_fill_color(*border_color)
    pdf.rect(x, y, 1.5, box_h, "F")
    
    # Thin outer border
    pdf.set_draw_color(*PDFTheme.COLOR_DIVIDER)
    pdf.set_line_width(0.3)
    pdf.rect(x, y, w, box_h, "D")
    
    # Text
    pdf.set_xy(x + 5, y + 4)
    pdf.set_font(PDFTheme.FONT_FAMILY, text_style, 10)
    pdf.set_text_color(*PDFTheme.COLOR_TEXT)
    pdf.multi_cell(w_content, 5.5, _to_latin1(text), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_y(y + box_h + 4)


# ---------------- RISK MATRIX RENDERER ----------------
def render_risks_table(pdf, block_content):
    """Convert risk bullets into a professional two-column mitigating table."""
    items = parse_list_items(block_content)
    table_rows = [["Risk Event / Vulnerability", "Mitigation Strategy"]]
    
    for item in items:
        text = item["text"]
        parts = re.split(r'(?i)(?:Mitigation|Response):\s*', text)
        if len(parts) >= 2:
            risk_desc = parts[0].strip().rstrip('.')
            mitigation_desc = parts[1].strip()
            table_rows.append([risk_desc, mitigation_desc])
        else:
            table_rows.append([text, "Implement standard continuous verification check."])
            
    # Set up headings Face
    from fpdf.fonts import FontFace
    heading_face = FontFace(
        fill_color=PDFTheme.COLOR_TABLE_HEADER_FILL,
        color=PDFTheme.COLOR_TABLE_HEADER_TEXT,
        emphasis="B"
    )
    pdf.set_font(PDFTheme.FONT_FAMILY, "", 8.5)
    col_widths = [pdf.epw * 0.45, pdf.epw * 0.55]
    
    pdf.check_page_break(len(table_rows) * 11 + 10)
    
    pdf.set_draw_color(*PDFTheme.COLOR_TABLE_BORDER)
    pdf.set_line_width(0.2)
    pdf.set_fill_color(*PDFTheme.COLOR_TABLE_CELL_FILL_EVEN)
    with pdf.table(
        rows=table_rows,
        align="CENTER",
        v_align="MIDDLE",
        padding=2.5,
        markdown=False,
        col_widths=col_widths,
        cell_fill_color=PDFTheme.COLOR_TABLE_CELL_FILL_EVEN,
        cell_fill_mode="EVEN_ROWS",
        headings_style=heading_face,
        min_row_height=8.0
    ) as table:
        pass
        
    pdf.set_font(PDFTheme.FONT_FAMILY, "", PDFTheme.SIZE_BODY)
    pdf.ln(4)


# ---------------- CHECKBOX BULLETS DRAWING ----------------
def draw_checkbox(pdf, x, y, checked=False, size=3.2):
    """Draw a vector checklist square box."""
    pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
    pdf.set_line_width(0.4)
    pdf.rect(x, y, size, size, "D")
    if checked:
        pdf.set_fill_color(*PDFTheme.COLOR_PRIMARY)
        pdf.rect(x + 0.6, y + 0.6, size - 1.2, size - 1.2, "F")


# ---------------- SEMANTIC PARSING UTILITIES ----------------
def parse_markdown_to_blocks(content: str):
    """Group lines into logical markdown block objects."""
    content = content.replace("\r\n", "\n")
    raw_lines = content.split("\n")
    
    blocks = []
    current_block_type = None
    current_block_lines = []
    
    def flush_block():
        nonlocal current_block_type, current_block_lines
        if not current_block_lines:
            return
        block_text = "\n".join(current_block_lines)
        if current_block_type == "table":
            blocks.append({"type": "table", "content": block_text})
        elif current_block_type == "list":
            blocks.append({"type": "list", "content": block_text})
        elif current_block_type == "blockquote":
            blocks.append({"type": "blockquote", "content": block_text})
        else:
            stripped = block_text.strip()
            if stripped.startswith("#"):
                level = len(stripped) - len(stripped.lstrip('#'))
                blocks.append({"type": "heading", "content": stripped, "level": level})
            else:
                blocks.append({"type": "paragraph", "content": block_text})
        current_block_lines = []
        current_block_type = None

    for line in raw_lines:
        line_stripped = line.strip()
        if not line_stripped:
            flush_block()
            continue
            
        if line_stripped.startswith("|") and line_stripped.endswith("|"):
            if current_block_type != "table":
                flush_block()
                current_block_type = "table"
            current_block_lines.append(line_stripped)
        elif line_stripped.startswith(">"):
            if current_block_type != "blockquote":
                flush_block()
                current_block_type = "blockquote"
            current_block_lines.append(line_stripped)
        elif (re.match(r'^([-*+])\s+', line_stripped) or 
              re.match(r'^\d+\.\s+', line_stripped) or
              re.match(r'^\s+([-*+])\s+', line) or
              re.match(r'^\s+\d+\.\s+', line)):
            if current_block_type != "list":
                flush_block()
                current_block_type = "list"
            current_block_lines.append(line)
        elif line_stripped.startswith("#"):
            flush_block()
            current_block_lines.append(line_stripped)
            flush_block()
        else:
            if current_block_type in ["table", "list", "blockquote", "heading"]:
                flush_block()
            current_block_type = "paragraph"
            current_block_lines.append(line)
            
    flush_block()
    return blocks


def parse_list_items(block_text: str):
    """Convert a raw list block into typed structured list items."""
    items = []
    lines = block_text.split("\n")
    for line in lines:
        if not line.strip():
            continue
        indent_spaces = len(line) - len(line.lstrip())
        level = indent_spaces // 2
        line_clean = line.strip()
        
        num_match = re.match(r'^(\d+)[.)]\s+(.+)', line_clean)
        bullet_match = re.match(r'^([-*+])\s+(.+)', line_clean)
        
        if num_match:
            marker, text = num_match.groups()
            is_number = True
        elif bullet_match:
            marker, text = bullet_match.groups()
            is_number = False
        else:
            marker, text = "-", line_clean
            is_number = False
            
        checked = False
        is_checkbox = False
        if text.startswith("[ ]"):
            is_checkbox = True
            checked = False
            text = text[3:].strip()
        elif text.startswith("[x]") or text.startswith("[X]"):
            is_checkbox = True
            checked = True
            text = text[3:].strip()
            
        items.append({
            "text": text,
            "marker": marker,
            "is_number": is_number,
            "is_checkbox": is_checkbox,
            "checked": checked,
            "level": level
        })
    return items


def get_semantic_sections(content: str):
    """Classify blocks into semantic section groupings."""
    blocks = parse_markdown_to_blocks(content)
    current_section_type = "standard"
    sections = []
    
    for block in blocks:
        b_type = block["type"]
        b_content = block["content"]
        
        if b_type == "heading":
            h_text = b_content.lstrip("#").strip().replace("**", "").replace("*", "")
            h_lower = h_text.lower()
            
            if "executive summary" in h_lower or "briefing" in h_lower:
                current_section_type = "executive_summary"
            elif "objective" in h_lower or "target" in h_lower or "goal" in h_lower:
                current_section_type = "objectives"
            elif "recommendation" in h_lower or "strategy" in h_lower:
                current_section_type = "recommendations"
            elif "risk" in h_lower or "threat" in h_lower or "mitigation" in h_lower:
                current_section_type = "risks"
            elif "assumption" in h_lower or "premise" in h_lower:
                current_section_type = "assumptions"
            elif "deliverable" in h_lower or "scope" in h_lower:
                current_section_type = "deliverables"
            elif "timeline" in h_lower or "roadmap" in h_lower or "schedule" in h_lower or "phases" in h_lower:
                current_section_type = "timeline"
            elif "metric" in h_lower or "kpi" in h_lower or "roi" in h_lower or "success" in h_lower:
                current_section_type = "metrics"
            else:
                if block.get("level", 2) < 3:
                    current_section_type = "standard"
                
            sections.append({
                "type": "heading",
                "content": h_text,
                "level": len(b_content) - len(b_content.lstrip("#")),
                "section_type": current_section_type
            })
        else:
            sections.append({
                "type": b_type,
                "content": b_content,
                "section_type": current_section_type
            })
            
    return sections


# ---------------- MAIN PDF EXPORT PIPELINE ----------------
def _generate_pdf(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    import time
    from app.config import DEBUG_TIMING
    if DEBUG_TIMING:
        logger.info("[INSTRUMENTATION] PDF generation start: timestamp=%f", time.time())
        
    gen_date = datetime.now().strftime("%B %d, %Y")
    
    # Clean H1 title if present
    extracted_title = ""
    for line in content.split('\n'):
        line_strip = line.strip()
        h1_match = re.match(r'^#\s+(.+)', line_strip)
        h1_alt_match = re.match(r'^##\s+(.+)', line_strip)
        if h1_match or h1_alt_match:
            match_obj = h1_match if h1_match else h1_alt_match
            extracted_title = match_obj.group(1).strip().replace('**', '').replace('*', '')
            break
            
    if extracted_title:
        title = extracted_title
    else:
        clean_type = document_type.replace('_', ' ').title()
        if len(title) > 60 or "." in title or "," in title:
            lower_title = title.lower()
            if "onboarding" in lower_title:
                title = f"Customer Onboarding {clean_type}"
            elif "activation" in lower_title:
                title = f"Customer Activation {clean_type}"
            elif "experience" in lower_title:
                title = f"Customer Experience {clean_type}"
            elif "retention" in lower_title:
                title = f"Customer Retention {clean_type}"
            else:
                words = [w for w in title.split() if w.lower() not in ["a", "an", "the", "we", "need", "to", "create", "generate", "write", "develop", "provide", "design", "draft"]]
                short_title = " ".join(words[:4]).strip(" ,.-/\\")
                title = f"{short_title.title()} {clean_type}"
                
    pdf = PDF(doc_title=title, doc_type=document_type, gen_date=gen_date)
    pdf.set_margins(PDFTheme.MARGIN_LEFT, PDFTheme.MARGIN_TOP, PDFTheme.MARGIN_RIGHT)
    pdf.set_auto_page_break(auto=True, margin=22.0)
    
    # ---------------- 1. MCKINSEY-STYLE COVER PAGE ----------------
    pdf.add_page()
    pdf.set_auto_page_break(auto=False)
    
    # Solid vertical accent bar (left spine)
    pdf.set_fill_color(*PDFTheme.COLOR_PRIMARY)
    pdf.rect(0, 0, 16, pdf.h, "F")
    
    # Clean background fill for remaining page (#F4F6F4)
    pdf.set_fill_color(244, 246, 244)
    pdf.rect(16, 0, pdf.w - 16, pdf.h, "F")
    
    # Cover page margins
    pdf.set_left_margin(32)
    pdf.set_right_margin(24)
    pdf.set_x(32)
    
    # Logo Monogram & Typographic Wordmark
    pdf.set_y(40)
    pdf.set_fill_color(*PDFTheme.COLOR_PRIMARY)
    pdf.rect(32, 40, 11, 11, "F")
    pdf.set_font("helvetica", "B", 6.5)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(32, 43.5)
    pdf.cell(11, 4, "AD", align="C")
    
    pdf.set_font("helvetica", "B", 10.5)
    pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
    pdf.set_xy(46, 43.5)
    pdf.cell(100, 4, "AgentDoc AI Workspace", align="L")
    
    # Document type uppercase
    pdf.set_xy(32, 90)
    pdf.set_font(PDFTheme.FONT_FAMILY, "B", 10.5)
    pdf.set_text_color(*PDFTheme.COLOR_SECONDARY)
    pdf.cell(0, 5, _to_latin1(document_type.upper().replace('_', ' ')), align="L")
    
    # Title Serif Bold (Times New Roman)
    pdf.set_xy(32, 98)
    pdf.set_font("times", "B", 26)
    pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
    pdf.multi_cell(0, 11, _to_latin1(title), align="L")
    
    # Thick Forest Green divider rule
    divider_y = pdf.get_y() + 6
    pdf.set_draw_color(*PDFTheme.COLOR_PRIMARY)
    pdf.set_line_width(1.5)
    pdf.line(32, divider_y, 85, divider_y)
    
    # Client Placeholder subtitle
    pdf.set_xy(32, divider_y + 8)
    pdf.set_font(PDFTheme.FONT_FAMILY, "I", 11)
    pdf.set_text_color(*PDFTheme.COLOR_TEXT)
    pdf.cell(0, 5, _to_latin1("Prepared for: Strategic Executive Stakeholders"), align="L")
    
    # Bottom metadata columns
    pdf.set_y(232)
    pdf.set_x(32)
    col_w = (pdf.w - 56) / 3
    
    pdf.set_font(PDFTheme.FONT_FAMILY, "B", 7.5)
    pdf.set_text_color(*PDFTheme.COLOR_SECONDARY)
    pdf.cell(col_w, 4, "CLASSIFICATION", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_w, 4, "PREPARED BY", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_w, 4, "DATE OF ISSUE", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(1.5)
    pdf.set_x(32)
    pdf.set_font(PDFTheme.FONT_FAMILY, "", 9)
    pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
    pdf.cell(col_w, 4, "Confidential / Executive", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_w, 4, "AgentDoc Services", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_w, 4, gen_date, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Restore standard margins & auto breaks
    pdf.set_left_margin(PDFTheme.MARGIN_LEFT)
    pdf.set_right_margin(PDFTheme.MARGIN_RIGHT)
    pdf.set_auto_page_break(auto=True, margin=22.0)
    
    # ---------------- 2. CONTENT PAGES (SECTIONS RENDERING) ----------------
    pdf.add_page()
    
    # Semantic block classification
    blocks = get_semantic_sections(content)
    
    # Step A: Collect and pre-render Executive Summary blocks at the top of content page
    summary_blocks = [b for b in blocks if b["section_type"] == "executive_summary" and b["type"] != "heading"]
    other_blocks = [b for b in blocks if b["section_type"] != "executive_summary" or b["type"] == "heading"]
    
    if summary_blocks:
        pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_H1)
        pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
        pdf.multi_cell(0, PDFTheme.LEAD_H1, _to_latin1("Executive Summary"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)
        render_executive_summary_panel(pdf, summary_blocks)
        
    # Step B: Render other blocks semantically
    idx = 0
    while idx < len(other_blocks):
        b = other_blocks[idx]
        b_type = b["type"]
        b_content = b["content"]
        sec_type = b["section_type"]
        
        # Skip empty blocks
        if not b_content.strip():
            idx += 1
            continue
            
        if b_type == "heading":
            h_text = b_content
            h_level = b["level"]
            
            # Skip double printing title heading at top of content
            if idx < 3 and (h_text.lower() in title.lower() or title.lower() in h_text.lower() or "executive summary" in h_text.lower()):
                idx += 1
                continue
                
            if h_level == 1:
                pdf.check_page_break(25)
                # Section horizontal rule divider
                if pdf.page_no() > 2 or (pdf.page_no() == 2 and pdf.get_y() > pdf.t_margin + 15):
                    pdf.ln(3)
                    pdf.set_draw_color(*PDFTheme.COLOR_DIVIDER)
                    pdf.set_line_width(0.3)
                    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
                    pdf.ln(5)
                
                # Draw Vector Icon next to section heading
                icon_y = pdf.get_y() + 1.2
                draw_heading_icon(pdf, sec_type, pdf.l_margin, icon_y, size=4.2)
                
                pdf.set_left_margin(PDFTheme.MARGIN_LEFT + 7.5)
                pdf.set_x(PDFTheme.MARGIN_LEFT + 7.5)
                pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_H1)
                pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
                pdf.multi_cell(0, PDFTheme.LEAD_H1, _to_latin1(h_text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_left_margin(PDFTheme.MARGIN_LEFT)
                pdf.ln(4)
                
            elif h_level in [2, 3] and sec_type == "timeline" and h_text.lower().startswith("phase"):
                # Check for Phase card timeline groupings
                # Look ahead: if next block is a List block, combine them into a Phase Card!
                phase_lines = []
                if idx + 1 < len(other_blocks) and other_blocks[idx + 1]["type"] == "list":
                    list_b = other_blocks[idx + 1]
                    phase_lines = [l.strip() for l in list_b["content"].split("\n") if l.strip()]
                    idx += 1 # Consume list block
                else:
                    phase_lines = ["Objective: Execute defined timeline roadmap steps."]
                
                draw_phase_card(pdf, h_text, phase_lines)
                idx += 1
                continue
                
            elif h_level == 2:
                pdf.check_page_break(18)
                pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_H2)
                pdf.set_text_color(*PDFTheme.COLOR_SECONDARY)
                pdf.multi_cell(0, PDFTheme.LEAD_H2, _to_latin1(h_text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(3)
                
            else:
                pdf.check_page_break(14)
                pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_H3)
                pdf.set_text_color(*PDFTheme.COLOR_SECONDARY)
                pdf.multi_cell(0, PDFTheme.LEAD_H3, _to_latin1(h_text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(2.5)
                
        elif b_type == "list":
            # Semantic risks matrix redirection
            if sec_type == "risks":
                render_risks_table(pdf, b_content)
                idx += 1
                continue
                
            items = parse_list_items(b_content)
            for item in items:
                pdf.check_page_break(11)
                
                # Dynamic list item indentation
                list_indent = PDFTheme.MARGIN_LEFT + (item["level"] * 6) + 6
                marker_pos = PDFTheme.MARGIN_LEFT + (item["level"] * 6)
                
                pdf.set_left_margin(list_indent)
                pdf.set_x(marker_pos)
                
                if item["is_checkbox"] or sec_type in ["assumptions", "deliverables"]:
                    # Draw visual square checklist box
                    draw_checkbox(pdf, marker_pos, pdf.get_y() + 1.2, checked=item["checked"] or sec_type == "deliverables", size=3.2)
                    pdf.set_x(list_indent)
                else:
                    pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_BODY)
                    pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
                    if item["is_number"]:
                        pdf.write(PDFTheme.LEAD_BODY, _to_latin1(f"{item['marker']}. "))
                    else:
                        pdf.write(PDFTheme.LEAD_BODY, _to_latin1("\x95  "))
                        
                pdf.set_font(PDFTheme.FONT_FAMILY, "", PDFTheme.SIZE_BODY)
                pdf.set_text_color(*PDFTheme.COLOR_TEXT)
                pdf.multi_cell(0, PDFTheme.LEAD_BODY, _to_latin1(item["text"]), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_left_margin(PDFTheme.MARGIN_LEFT)
                pdf.ln(1)
                
            pdf.ln(2)
            
        elif b_type == "table":
            # Standard Markdown Table parser
            table_rows = []
            for row_line in b_content.split("\n"):
                row_line = row_line.strip()
                if row_line.startswith("|") and row_line.endswith("|"):
                    if not re.match(r'^\|[\s\-:|]+\|$', row_line):
                        cells = [c.strip() for c in row_line.strip("|").split("|")]
                        if cells and cells[0] == "":
                            cells = cells[1:]
                        if cells and cells[-1] == "":
                            cells = cells[:-1]
                        table_rows.append(cells)
            
            if table_rows:
                try:
                    from fpdf.fonts import FontFace
                    heading_face = FontFace(
                        fill_color=PDFTheme.COLOR_TABLE_HEADER_FILL,
                        color=PDFTheme.COLOR_TABLE_HEADER_TEXT,
                        emphasis="B"
                    )
                    
                    cleaned_rows = []
                    for row in table_rows:
                        cleaned_row = []
                        for cell in row:
                            cell_cleaned = _clean_all_markdown_for_tables(cell)
                            cell_cleaned = _to_latin1(cell_cleaned)
                            cleaned_row.append(cell_cleaned)
                        cleaned_rows.append(cleaned_row)
                        
                    pdf.set_font(PDFTheme.FONT_FAMILY, "", 8.5)
                    pdf.set_text_color(*PDFTheme.COLOR_TEXT)
                    
                    num_cols = len(cleaned_rows[0])
                    cell_padding = 2.5
                    
                    col_max_widths = [0.0] * num_cols
                    col_max_word_widths = [0.0] * num_cols
                    for row in cleaned_rows:
                        for col_idx, cell in enumerate(row):
                            if col_idx < num_cols:
                                str_w = pdf.get_string_width(cell)
                                col_max_widths[col_idx] = max(col_max_widths[col_idx], str_w)
                                words = cell.split()
                                word_w = max(pdf.get_string_width(w) for w in words) if words else 0.0
                                col_max_word_widths[col_idx] = max(col_max_word_widths[col_idx], word_w)
                                
                    total_text_w = sum(col_max_widths)
                    usable_width = pdf.epw
                    
                    if total_text_w > 0:
                        col_widths = [(w / total_text_w) * usable_width for w in col_max_widths]
                        for col_i in range(num_cols):
                            word_limit = col_max_word_widths[col_i] + (2 * cell_padding) + 1.0
                            hard_min = max(25.0, usable_width * 0.12)
                            col_min = max(word_limit, hard_min)
                            if col_widths[col_i] < col_min:
                                col_widths[col_i] = col_min
                        total_w = sum(col_widths)
                        if total_w > usable_width:
                            col_widths = [(w / total_w) * usable_width for w in col_widths]
                        else:
                            remaining = usable_width - total_w
                            if remaining > 0:
                                col_widths = [w + (col_max_widths[col_i] / total_text_w) * remaining for col_i, w in enumerate(col_widths)]
                    else:
                        col_widths = None
                        
                    estimated_height = len(cleaned_rows) * 11
                    pdf.check_page_break(estimated_height if estimated_height < 60 else 30)
                    
                    pdf.set_draw_color(*PDFTheme.COLOR_TABLE_BORDER)
                    pdf.set_line_width(0.2)
                    pdf.set_fill_color(*PDFTheme.COLOR_TABLE_CELL_FILL_EVEN)
                    with pdf.table(
                        rows=cleaned_rows,
                        align="CENTER",
                        v_align="MIDDLE",
                        padding=cell_padding,
                        markdown=False,
                        col_widths=col_widths,
                        cell_fill_color=PDFTheme.COLOR_TABLE_CELL_FILL_EVEN,
                        cell_fill_mode="EVEN_ROWS",
                        headings_style=heading_face,
                        min_row_height=8.0
                    ) as table:
                        pass
                    
                    pdf.set_font(PDFTheme.FONT_FAMILY, "", PDFTheme.SIZE_BODY)
                    pdf.ln(4)
                except Exception as ex:
                    logger.error("Error rendering table to PDF: %s", ex)
                    
        elif b_type == "blockquote":
            # Clean blockquote marker '>'
            text = b_content.lstrip(">").strip()
            render_callout_box(pdf, text, PDFTheme.COLOR_SECONDARY, (244, 246, 244), text_style="I")
            
        else:
            # Semantic Objectives Redirect
            if sec_type == "objectives" and len(b_content) > 30:
                render_callout_box(pdf, b_content, PDFTheme.COLOR_PRIMARY, (244, 246, 244))
                idx += 1
                continue
                
            # Paragraph Block Rendering
            lines = [l.strip() for l in b_content.split("\n") if l.strip()]
            for line in lines:
                pdf.check_page_break(12)
                
                # Check for inline bullet formatting
                if line.startswith("- ") or line.startswith("* "):
                    pdf.set_left_margin(PDFTheme.MARGIN_LEFT + 6)
                    pdf.set_x(PDFTheme.MARGIN_LEFT)
                    pdf.set_font(PDFTheme.FONT_FAMILY, "B", PDFTheme.SIZE_BODY)
                    pdf.set_text_color(*PDFTheme.COLOR_PRIMARY)
                    pdf.write(PDFTheme.LEAD_BODY, _to_latin1("\x95  "))
                    pdf.set_font(PDFTheme.FONT_FAMILY, "", PDFTheme.SIZE_BODY)
                    pdf.set_text_color(*PDFTheme.COLOR_TEXT)
                    pdf.multi_cell(0, PDFTheme.LEAD_BODY, _to_latin1(line[2:]), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                    pdf.set_left_margin(PDFTheme.MARGIN_LEFT)
                    pdf.ln(1)
                else:
                    pdf.set_font(PDFTheme.FONT_FAMILY, "", PDFTheme.SIZE_BODY)
                    pdf.set_text_color(*PDFTheme.COLOR_TEXT)
                    pdf.multi_cell(0, PDFTheme.LEAD_BODY, _to_latin1(line), markdown=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                    pdf.ln(2.5)
            pdf.ln(1.5)
            
        idx += 1
        
    if DEBUG_TIMING:
        logger.info("[INSTRUMENTATION] PDF save/write start: timestamp=%f", time.time())
        
    pdf.output(str(filepath))
    
    return filename


def _clean_markdown_preserving_formatting(text: str) -> str:
    """Remove code blocks and links, but preserve bold and italic markers."""
    text = re.sub(r'`(.+?)`', r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    return text.strip()


def _clean_all_markdown_for_tables(text: str) -> str:
    """Remove code blocks, links, bold, and italic markers completely for tables."""
    text = re.sub(r'`(.+?)`', r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    text = text.replace('**', '').replace('*', '')
    return text.strip()


def _break_long_words(text: str, max_length: int = 50) -> str:
    """Break long sequences of non-whitespace characters to prevent PDF rendering errors."""
    return re.sub(r'(\S{' + str(max_length) + r'})', r'\1 ', text)


def _add_content_sections(doc: Document, content: str) -> None:
    """Parse and add content sections to the document.

    Handles headings (## / ###), bullet points (- / *), numbered lists,
    and tables (| ... |).
    """
    lines = content.split("\n")
    i = 0
    in_table = False
    table_rows: list[list[str]] = []

    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            if in_table and table_rows:
                _add_table(doc, table_rows)
                table_rows = []
                in_table = False
            i += 1
            continue

        # Table detection
        if line.startswith("|") and line.endswith("|"):
            # Skip separator rows
            if re.match(r'^\|[\s\-:|]+\|$', line):
                i += 1
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            # Filter out empty cells at the start and end due to leading/trailing |
            if cells and cells[0] == "":
                cells = cells[1:]
            if cells and cells[-1] == "":
                cells = cells[:-1]
            table_rows.append(cells)
            in_table = True
            i += 1
            continue

        # Flush any pending table
        if in_table and table_rows:
            _add_table(doc, table_rows)
            table_rows = []
            in_table = False

        # Heading level 1 (##)
        if line.startswith("## "):
            heading_text = line[3:].strip()
            # Clean any markdown bold markers
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=1)
            i += 1
            continue

        # Heading level 2 (###)
        if line.startswith("### "):
            heading_text = line[4:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=2)
            i += 1
            continue

        # Heading level 3 (####)
        if line.startswith("#### "):
            heading_text = line[5:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=3)
            i += 1
            continue

        # Bullet points
        if line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            text = _clean_markdown(text)
            _add_paragraph_with_formatting(doc, text, style='List Bullet')
            i += 1
            continue

        # Numbered list (e.g., "1. ", "2. ")
        match = re.match(r'^(\d+)\.\s+(.+)', line)
        if match:
            text = _clean_markdown(match.group(2))
            _add_paragraph_with_formatting(doc, text, style='List Number')
            i += 1
            continue

        # Regular paragraph
        text = _clean_markdown(line)
        if text:
            _add_paragraph_with_formatting(doc, text)

        i += 1

    # Flush final table
    if table_rows:
        _add_table(doc, table_rows)


def _add_paragraph_with_formatting(doc: Document, text: str, style=None):
    """Add a paragraph while parsing inline bold markdown."""
    p = doc.add_paragraph(style=style)
    parts = re.split(r'(\*\*.*?\*\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = p.add_run(part[2:-2])
            run.bold = True
        else:
            p.add_run(part)
    return p


def _add_table(doc: Document, rows: list[list[str]]) -> None:
    """Add a table to the document."""
    if not rows:
        return

    num_cols = max(len(r) for r in rows)
    if num_cols == 0:
        return
        
    table = doc.add_table(rows=len(rows), cols=num_cols)
    table.style = 'Light Shading Accent 1'

    for r_idx, row_data in enumerate(rows):
        for c_idx, cell_text in enumerate(row_data):
            if c_idx < num_cols:
                cell = table.cell(r_idx, c_idx)
                cell.text = "" # Clear default
                p = cell.paragraphs[0]
                text = _clean_markdown(cell_text)
                
                parts = re.split(r'(\*\*.*?\*\*)', text)
                for part in parts:
                    if part.startswith('**') and part.endswith('**'):
                        run = p.add_run(part[2:-2])
                        run.bold = True
                    else:
                        p.add_run(part)
                        
                # Bold header row
                if r_idx == 0:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True

    doc.add_paragraph()  # Spacer after table


def _clean_markdown(text: str) -> str:
    """Remove common markdown formatting from text, preserving bold."""
    # Remove inline code
    text = re.sub(r'`(.+?)`', r'\1', text)
    # Remove markdown links, keep text
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    return text.strip()


def _editorial_cleanup_pass(text: str) -> str:
    """Lightweight editorial pass to fix formatting, spacing, and punctuation issues."""
    if not text:
        return ""
    # 1. Remove repeated periods
    text = re.sub(r'\.{2,}', '.', text)
    # 2. Remove duplicate commas
    text = re.sub(r',{2,}', ',', text)
    # 3. Correct spacing around punctuation: space after punctuation, no space before
    text = re.sub(r'\s+([.,;:!?])', r'\1', text)
    # Ensure space after punctuation (but not if followed by a number or punctuation)
    text = re.sub(r'([.,;:!?])(?=[A-Za-z])', r'\1 ', text)
    # 4. Clean up typical spelling or spacing bugs
    text = re.sub(r'\bcore\s+issueunknown\b', 'core issue: unknown', text)
    # 5. Ensure headings don't have trailing punctuation like periods
    lines = []
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            if stripped.endswith("."):
                line = line.rstrip(".")
        lines.append(line)
    text = "\n".join(lines)
    return text
