"""Document tool for deterministic DOCX generation.

Uses python-docx to create professional Word documents
from synthesized content.
"""

import logging
import re
from datetime import datetime
from pathlib import Path
import markdown
from fpdf import FPDF

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.config import OUTPUT_DIR

logger = logging.getLogger(__name__)


def sanitize_filename(name: str) -> str:
    """Create a safe filename from a string."""
    # Remove unsafe characters
    safe = re.sub(r'[^\w\s-]', '', name.lower())
    safe = re.sub(r'[\s]+', '_', safe.strip())
    # Truncate to reasonable length
    return safe[:50] if safe else "document"


def generate_docx(
    title: str,
    document_type: str,
    assumptions: list[str],
    content: str,
    goal: str,
    format_ext: str = "docx"
) -> str:
    """Generate a professional document in the requested format.

    Args:
        title: Document title
        document_type: Type of document being generated
        assumptions: List of assumptions made
        content: The synthesized document content
        goal: The interpreted goal

    Returns:
        The filename of the generated document.
    """
    OUTPUT_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_type = sanitize_filename(document_type)
    
    # Normalize format
    fmt = format_ext.lower().strip('.')
    if fmt not in ["docx", "pdf", "html", "md", "markdown"]:
        fmt = "docx"
        
    filename = f"agentdoc_{safe_type}_{timestamp}.{fmt}"
    filepath = OUTPUT_DIR / filename

    if fmt in ["md", "markdown"]:
        return _generate_markdown(filepath, title, document_type, assumptions, content, goal, filename)
    elif fmt == "html":
        return _generate_html(filepath, title, document_type, assumptions, content, goal, filename)
    elif fmt == "pdf":
        return _generate_pdf(filepath, title, document_type, assumptions, content, goal, filename)

    doc = Document()

    # --- Styles ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # --- Title ---
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- Subtitle ---
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Document Type: {document_type.replace('_', ' ').title()}")
    run.font.size = Pt(12)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # --- Date ---
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    date_run.font.size = Pt(10)
    date_run.font.color.rgb = RGBColor(130, 130, 130)

    doc.add_paragraph()  # Spacer

    # --- Goal / Executive Summary ---
    if goal:
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(goal)

    # --- Assumptions ---
    if assumptions:
        doc.add_heading("Key Assumptions", level=1)
        for assumption in assumptions:
            p = doc.add_paragraph(assumption, style='List Bullet')
            p.paragraph_format.space_after = Pt(4)

    # --- Main Content ---
    _add_content_sections(doc, content)

    # --- Footer ---
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by AgentDoc — Autonomous Document Generation Agent")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)
    footer_run.font.italic = True

    doc.save(str(filepath))
    logger.info("Generated DOCX: %s", filename)
    return filename


def _generate_markdown(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    lines = [
        f"# {title}",
        f"**Document Type:** {document_type.replace('_', ' ').title()}",
        f"**Generated:** {datetime.now().strftime('%B %d, %Y')}",
        ""
    ]
    if goal:
        lines.extend(["## Executive Summary", goal, ""])
    if assumptions:
        lines.extend(["## Key Assumptions"])
        lines.extend([f"- {a}" for a in assumptions])
        lines.extend([""])
        
    lines.append(content)
    lines.extend([
        "",
        "---",
        "*Generated by AgentDoc — Autonomous Document Generation Agent*"
    ])
    
    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filename


def _generate_html(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    md_text = _generate_markdown(filepath, title, document_type, assumptions, content, goal, filename)
    # Read the markdown back
    md_content = filepath.read_text(encoding="utf-8")
    
    html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
    
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
    h1 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
    h2 {{ color: #34495e; margin-top: 30px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
    th {{ background-color: #f8f9fa; font-weight: 600; }}
    hr {{ border: 0; border-top: 1px solid #eee; margin: 40px 0; }}
    .footer {{ color: #888; font-size: 0.9em; text-align: center; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""

    filepath.write_text(html, encoding="utf-8")
    return filename


def _generate_pdf(filepath: Path, title: str, document_type: str, assumptions: list[str], content: str, goal: str, filename: str) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("helvetica", "B", 24)
    pdf.cell(0, 15, title.encode('latin-1', 'replace').decode('latin-1'), ln=True, align='C')
    
    # Subtitle
    pdf.set_font("helvetica", "I", 12)
    pdf.set_text_color(100, 100, 100)
    subtitle = f"Document Type: {document_type.replace('_', ' ').title()}"
    pdf.cell(0, 10, subtitle.encode('latin-1', 'replace').decode('latin-1'), ln=True, align='C')
    
    # Date
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(130, 130, 130)
    date_str = f"Generated: {datetime.now().strftime('%B %d, %Y')}"
    pdf.cell(0, 10, date_str.encode('latin-1', 'replace').decode('latin-1'), ln=True, align='C')
    
    pdf.ln(10)
    
    # Exec Summary
    pdf.set_text_color(0, 0, 0)
    if goal:
        pdf.set_font("helvetica", "B", 16)
        pdf.cell(0, 10, "Executive Summary", ln=True)
        pdf.set_font("helvetica", "", 11)
        pdf.multi_cell(0, 6, goal.encode('latin-1', 'replace').decode('latin-1'))
        pdf.ln(5)
        
    # Assumptions
    if assumptions:
        pdf.set_font("helvetica", "B", 16)
        pdf.cell(0, 10, "Key Assumptions", ln=True)
        pdf.set_font("helvetica", "", 11)
        for a in assumptions:
            pdf.multi_cell(0, 6, f"- {a}".encode('latin-1', 'replace').decode('latin-1'))
        pdf.ln(5)
        
    # Content - very basic Markdown to PDF for FPDF
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
            
        if line.startswith('## '):
            pdf.set_font("helvetica", "B", 16)
            pdf.cell(0, 10, line[3:].replace('**','').encode('latin-1', 'replace').decode('latin-1'), ln=True)
        elif line.startswith('### '):
            pdf.set_font("helvetica", "B", 14)
            pdf.cell(0, 8, line[4:].replace('**','').encode('latin-1', 'replace').decode('latin-1'), ln=True)
        elif line.startswith('#### '):
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 7, line[5:].replace('**','').encode('latin-1', 'replace').decode('latin-1'), ln=True)
        elif line.startswith('- ') or line.startswith('* '):
            pdf.set_font("helvetica", "", 11)
            text = line[2:].replace('**', '')
            pdf.multi_cell(0, 6, f"  •  {text}".encode('latin-1', 'replace').decode('latin-1'))
        else:
            pdf.set_font("helvetica", "", 11)
            text = line.replace('**', '')
            pdf.multi_cell(0, 6, text.encode('latin-1', 'replace').decode('latin-1'))

    pdf.output(str(filepath))
    return filename


def _add_content_sections(doc: Document, content: str) -> None:
    """Parse and add content sections to the document.

    Handles headings (## / ###), bullet points (- / *), numbered lists,
    and tables (| ... |).
    """
    lines = content.split("\n")
    i = 0
    in_table = False
    table_rows: list[list[str]] = []

    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            if in_table and table_rows:
                _add_table(doc, table_rows)
                table_rows = []
                in_table = False
            i += 1
            continue

        # Table detection
        if line.startswith("|") and line.endswith("|"):
            # Skip separator rows
            if re.match(r'^\|[\s\-:|]+\|$', line):
                i += 1
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            # Filter out empty cells at the start and end due to leading/trailing |
            if cells and cells[0] == "":
                cells = cells[1:]
            if cells and cells[-1] == "":
                cells = cells[:-1]
            table_rows.append(cells)
            in_table = True
            i += 1
            continue

        # Flush any pending table
        if in_table and table_rows:
            _add_table(doc, table_rows)
            table_rows = []
            in_table = False

        # Heading level 1 (##)
        if line.startswith("## "):
            heading_text = line[3:].strip()
            # Clean any markdown bold markers
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=1)
            i += 1
            continue

        # Heading level 2 (###)
        if line.startswith("### "):
            heading_text = line[4:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=2)
            i += 1
            continue

        # Heading level 3 (####)
        if line.startswith("#### "):
            heading_text = line[5:].strip()
            heading_text = heading_text.replace("**", "")
            doc.add_heading(heading_text, level=3)
            i += 1
            continue

        # Bullet points
        if line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            text = _clean_markdown(text)
            _add_paragraph_with_formatting(doc, text, style='List Bullet')
            i += 1
            continue

        # Numbered list (e.g., "1. ", "2. ")
        match = re.match(r'^(\d+)\.\s+(.+)', line)
        if match:
            text = _clean_markdown(match.group(2))
            _add_paragraph_with_formatting(doc, text, style='List Number')
            i += 1
            continue

        # Regular paragraph
        text = _clean_markdown(line)
        if text:
            _add_paragraph_with_formatting(doc, text)

        i += 1

    # Flush final table
    if table_rows:
        _add_table(doc, table_rows)


def _add_paragraph_with_formatting(doc: Document, text: str, style=None):
    """Add a paragraph while parsing inline bold markdown."""
    p = doc.add_paragraph(style=style)
    parts = re.split(r'(\*\*.*?\*\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = p.add_run(part[2:-2])
            run.bold = True
        else:
            p.add_run(part)
    return p


def _add_table(doc: Document, rows: list[list[str]]) -> None:
    """Add a table to the document."""
    if not rows:
        return

    num_cols = max(len(r) for r in rows)
    if num_cols == 0:
        return
        
    table = doc.add_table(rows=len(rows), cols=num_cols)
    table.style = 'Light Shading Accent 1'

    for r_idx, row_data in enumerate(rows):
        for c_idx, cell_text in enumerate(row_data):
            if c_idx < num_cols:
                cell = table.cell(r_idx, c_idx)
                cell.text = "" # Clear default
                p = cell.paragraphs[0]
                text = _clean_markdown(cell_text)
                
                parts = re.split(r'(\*\*.*?\*\*)', text)
                for part in parts:
                    if part.startswith('**') and part.endswith('**'):
                        run = p.add_run(part[2:-2])
                        run.bold = True
                    else:
                        p.add_run(part)
                        
                # Bold header row
                if r_idx == 0:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True

    doc.add_paragraph()  # Spacer after table


def _clean_markdown(text: str) -> str:
    """Remove common markdown formatting from text, preserving bold."""
    # Remove inline code
    text = re.sub(r'`(.+?)`', r'\1', text)
    # Remove markdown links, keep text
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    return text.strip()
